name: dotnet package

on: 
  push:
    branches:    
      - 'main'
  schedule:
    - cron: '0 0 1 * *'

jobs:
  build:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v1
        with:
         dotnet-version: '6.0.x'
         include-prerelease: true
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet publish -p:PublishReadyToRun=true -p:PublishSingleFile=true --no-self-contained -r win-x64 -c Release
      - name: Test
        run: dotnet test --no-restore --verbosity normal
      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
         name:  ApexAdaptive100Plus
         path:  bin\Release\net6.0-windows\win-x64\publish
        
